# Graphics
RENDER:
    mode: #"human"
    wait_timestep_ms: 700

# Grid
n_squares_width: 7
n_squares_height: 6

############################################
# Training
num_episodes: 100000
saving_freq: 50000
train_code: &train_code "J"

############################################
# Random
Random: &Random
    name: "Random"
    EPSILON: 1
    EPSILON_rateDecay: 1
    pickle_filename: ""

# RuleBased 
RuleBased: &RuleBased
    name: "RuleBased"
    EPSILON: 0.90
    EPSILON_rateDecay: 1
    pickle_filename: ""

# Q_learning parameters
Q_Learning: &Q_Learning
    name: "Q_Learning"
    EPSILON: 0.01
    EPSILON_rateDecay: "linear_over_episodes" #1 # Exploration rate decay
    ALPHA: 0.1 # Learning rate
    GAMMA: 0.9 # Discount factor
    pickle_filename: "outputs/q_learning_values"
    train_code: *train_code

# DQN parameters
DQN: &DQN
    name: "DQN"
    minibatch_size: 64 # Number of experiences to sample from memory
    replay_buffer_size: 10000
    target_update_freq: 1000
    EPSILON: 0.05 # Exploration rate
    EPSILON_rateDecay: 1 # Exploration rate decay
    ALPHA: 0.1 # Learning rate
    GAMMA: 0.9 # Discount factor
    pickle_filename: "outputs/dqn_values"
    train_code: *train_code

############################################
# Agents
player:
    max_hp: 50
    movement_speed: 5
    attack_damage: 10
    attacks_max_number: 1
    picture_path: "pictures/Erik combat pose-token.png"
    name: "Erik"
    default_coordinates: "random"
    algorithm: *Q_Learning # NEEDS to be an alias of the algorithm (the "*")

monster:
    max_hp: 100
    movement_speed: 3
    attack_damage: 10
    attacks_max_number: 2
    picture_path: "pictures/mimic2-token.png"
    name: "Mimic"
    default_coordinates: "random"
    algorithm: *RuleBased # NEEDS to be an alias of the algorithm (the "*")

# Reward System
advanced_reward: True

############################################

# Experiment A
# statistics_filename: "statistics/QL_A"
# + QL, Simple Reward, Mimic FullMovement FullAttacks, Mimic Random Strategy, 200k episodes

# Experiment B
# statistics_filename: "statistics/QL_B"
# + QL, Advanced Reward, Mimic FullMovement FullAttacks, Mimic Random Strategy, 200k episodes

# Experiment C
# statistics_filename: "statistics/QL_C"
# + QL, Simple Reward, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy, 200k episodes

# Experiment D
# statistics_filename: "statistics/QL_D"
# + QL, Advanced Reward, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy, 200k episodes

# Experiment E
# statistics_filename: "statistics/QL_E"
# + QL, Simple Reward, Mimic NoMovement NoAttacks, Mimic RuleBased Strategy, 50k episodes
# + QL, Simple Reward, Mimic FullMovement NoAttacks, Mimic RuleBased Strategy, 50k episodes
# + QL, Simple Reward, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy, 50k episodes

# Experiment F
# statistics_filename: "statistics/QL_F"
# + QL, Advanced Reward, Mimic NoMovement NoAttacks, Mimic RuleBased Strategy, 50k episodes
# + QL, Advanced Reward, Mimic FullMovement NoAttacks, Mimic RuleBased Strategy, 50k episodes
# + QL, Advanced Reward, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy, 50k episodes

# Experiment G
# statistics_filename: "statistics/QL_G"
# + QL, Simple Reward, Mimic NoMovement NoAttacks, Mimic RuleBased Strategy, 50k episodes
# + QL, Simple Reward, Mimic FullMovement NoAttacks, Mimic RuleBased Strategy, 50k episodes
# + QL, Simple Reward, Mimic FullMovement HalfAttacks HalfDamage, Mimic RuleBased Strategy, 150k episodes
# + QL, Simple Reward, Mimic FullMovement HalfAttacks FullDamage, Mimic RuleBased Strategy, 100k episodes
# (aborted here)
# + QL, Simple Reward, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy


# Experiment H
# statistics_filename: "statistics/QL_H"
# + QL, Simple Reward, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.95, 150k episodes
# + QL, Simple Reward, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.90, 100k episodes


# Experiment I
# statistics_filename: "statistics/QL_I"
# + QL, Simple Reward, Erik linear epsilon decay, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.90, 100k episodes
# + QL, Simple Reward, Erik linear epsilon decay, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.80, 100k episodes
# + QL, Simple Reward, Erik epsilon=0.01, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.80, 50k episodes


# Experiment J
statistics_filename: "statistics/QL_J"
# + QL, Advanced Reward, Erik linear epsilon decay, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.90, 100k episodes
# + QL, Advanced Reward, Erik linear epsilon decay, Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.80, 150k episodes
# + QL, Advanced Reward, Erik epsilon=0.01 , Mimic FullMovement FullAttacks, Mimic RuleBased Strategy with epsilon 0.80, 50k episodes