# Graphics
RENDER:
    mode: #"human"
    wait_timestep_ms: 100

# Grid
n_squares_width: 7
n_squares_height: 6

############################################
# Random
Random: &Random
    name: "Random"
    EPSILON: 1
    EPSILON_rateDecay: 1
    pickle_filename: ""

# Handcrafted 
Handcrafted: &Handcrafted
    name: "Handcrafted"
    EPSILON: 0
    EPSILON_rateDecay: 1
    pickle_filename: ""

# Q_learning parameters
Q_Learning: &Q_Learning
    name: "Q_Learning"
    EPSILON: 0.05
    EPSILON_rateDecay: 1 # Exploration rate decay
    ALPHA: 0.1 # Learning rate
    GAMMA: 0.9 # Discount factor
    pickle_filename: "outputs/q_learning_values.pkl"

# DQN parameters
DQN: &DQN
    name: "DQN"
    minibatch_size: 64 # Number of experiences to sample from memory
    replay_buffer_size: 10000
    target_update_freq: 1000
    EPSILON: 0.05 # Exploration rate
    EPSILON_rateDecay: 1 # Exploration rate decay
    ALPHA: 0.1 # Learning rate
    GAMMA: 0.9 # Discount factor
    pickle_filename: "outputs/dqn_values.pkl"

############################################
# Agents
player:
    max_hp: 50
    movement_speed: 5
    attack_damage: 10
    attacks_max_number: 1
    picture_path: "pictures/Erik combat pose-token.png"
    name: "Erik"
    default_coordinates: "random"
    algorithm: *Q_Learning # NEEDS to be an alias of the algorithm (the "*")

monster:
    max_hp: 100
    movement_speed: 3
    attack_damage: 10
    attacks_max_number: 2
    picture_path: "pictures/mimic2-token.png"
    name: "Mimic"
    default_coordinates: "random"
    algorithm: *Handcrafted # NEEDS to be an alias of the algorithm (the "*")

# Training
num_episodes: 100000
saving_freq: 100000
statistics_filename: "statistics/statistics"
