# Graphics
RENDER:
    mode: "human"
    wait_timestep_ms: 0

# Grid
n_squares_width: 6
n_squares_height: 5

# Agents
player:
    max_hp: 50
    movement_speed: 6
    attack_damage: 5
    attacks_max_number: 1
    picture_path: "pictures/Erik combat pose-token.png"
    name: "Erik"
    default_coordinates: "random"

monster:
    max_hp: 100
    movement_speed: 3
    attack_damage: 10
    attacks_max_number: 1
    picture_path: "pictures/mimic2-token.png"
    name: "Mimic"
    default_coordinates: "random"

# Q_learning parameters
Q_Learning: &Q_Learning
    name: "Q_Learning"
    EPSILON: 0.2 # Exploration rate
    ALPHA: 0.1 # Learning rate
    GAMMA: 0.9 # Discount factor
    pickle_filename: "outputs/q_learning_values.pkl"

# Training
num_episodes: 2
algorithm: *Q_Learning # NEEDS to be an alias of the algorithm (the "*")
