# Graphics
RENDER:
    mode: "human"
    wait_timestep_ms: 0

# Grid
n_squares_width: 6
n_squares_height: 5

# Agents
player:
    max_hp: 50
    movement_speed: 6
    attack_damage: 5
    attacks_max_number: 1
    picture_path: "pictures/Erik combat pose-token.png"
    default_coordinates: "random"

monster:
    max_hp: 100
    movement_speed: 3
    attack_damage: 10
    attacks_max_number: 1
    picture_path: "pictures/mimic2-token.png"
    default_coordinates: "random"


# Training
num_episodes : 100


# Q_learning parameters
Q_learning:
    EPSILON : 0.2  # Exploration rate
    ALPHA : 0.1  # Learning rate
    GAMMA : 0.9  # Discount factor